#!/bin/sh

# PLEASE READ ME: This builds a bootable iso, if you want a PXE bootable
# image change BINARY_IMAGE_TYPE parameter to "netboot"


set -e

# PXE Boot Image
BINARY_IMAGE_TYPE="netboot"

lb config noauto 					                  \
	--mode debian					                    \
	--distribution buster	   			            \
	--binary-images ${BINARY_IMAGE_TYPE}		  \
  --bootloaders 'syslinux'                  \
	--architectures amd64 				            \
	--archive-areas "main contrib non-free" 	\
	--debian-installer false 			            \
  --net-tarball true                        \
	--apt-indices false				                \
	--memtest none					                  \
	"${@}"
