#!/bin/sh

# PLEASE READ ME: This builds a bootable iso, if you want a PXE bootable
# image change BINARY_IMAGE_TYPE parameter to "netboot"


set -e

# PXE Boot Image
BINARY_IMAGE_TYPE="netboot"

# ISO Image
BINARY_IMAGE_TYPE="iso-hybrid"


lb config noauto 					\
	--mode debian					\
	--distribution stretch				\
	--binary-images ${BINARY_IMAGE_TYPE}		\
	--architectures amd64 				\
	--debian-installer false 			\
	--archive-areas "main contrib non-free" 	\
	--apt-indices false				\
	--memtest none					\
	"${@}"
